'''Raises TryNobreakError'''
d√©finir test_except_nobreak_():
    essayer:
        A = 1
    siexception:
        A = 2
    pasinterrompu:
        affirmer A = 1
